# Generated by Django 4.2.5 on 2023-09-14 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_item_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='title',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
