# Generated by Django 4.2.5 on 2023-09-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_item_title_delete_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='sub_item',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
