# Generated by Django 4.2.5 on 2023-09-14 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_title_alter_item_item_alter_subitem_sub_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subitem',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.item'),
        ),
    ]
